INSERT INTO book
    (title, image_book, file_book, download_allow, genre, author, created_at)
VALUES
    ('Капитанская дочка', 
    '/public/storage/books/kapitanskaya_dochka.pdf',
    '/public/storage/images/kapitanskaya_dochka.jpg',
    true,
    'Поэзия',
    'Александр Пушкин',
    '2024-05-01 13:15:30'),
    ('Евгений Онегин', 
    '/public/storage/books/evgeniy_onegin.pdf',
    '/public/storage/images/evgeniy_onegin.jpg',
    false,
    'Классика',
    'Александр Пушкин',
    '2024-05-03 12:17:10'),
    ('Война и мир', 
    '/public/storage/books/voina_i_mir.epub',
    '/public/storage/images/voina_i_mir.jpg',
    true,
    'Исторический жанр',
    'Лев Толстой',
    '2024-05-05 11:28:35'),
    ('1984', 
    '/public/storage/books/1984.pdf',
    '/public/storage/images/1984.jpg',
    true,
    'Антиутопия',
    'Джордж Оруэлл',
    '2024-05-03 18:17:10');
